### ISSUE TITLE
User list displays no users other than me :)

### ISSUE THREAD

**Issue by Hack5190** [adsr/irslackd#21]
irc_in CAP LS
irc_in PASS (TOKEN REMOVED)
irc_in NICK Hack5190
slack_out auth.test undefined
irc_in USER Hack5190 "Hack5190" "Hack5190" :Hack 5190
slack_out users.info { user: 'UAV3JGZ88' }
slack_in hello { type: 'hello' }
irc_out :irslackd 001 hack5190 irslackd
irc_out :irslackd 376 hack5190 :End of MOTD
slack_out users.setPresence { presence: 'auto' }
slack_out: refreshUsers
slack_out users.list {}
slack_out users.info { user: 'UAV3JGZ88' }
irc_in WHO hack5190
slack_in manual_presence_change { type: 'manual_presence_change',
  presence: 'active',
  event_ts: '1527252832.000576' }
irc_out :irslackd 311 = hack5190 hack5190 irslackd * :Hack 5190
irc_out :irslackd 318 = hack5190 :End of WHOIS list
slack_out usergroups.list { include_count: false,
  include_disabled: false,
  include_users: false }
slack_out: refreshChannels
slack_out conversations.list { types: 'public_channel,private_channel,mpim' }
slack_out: hydrateChannel general
slack_out conversations.members { channel: 'C9RBY2S4B' }
irc_out: joinChannel #general
irc_out :hack5190 JOIN #general
irc_out :irslackd 332 = #general :Testing and Support of irslackd - <https://github.com/adsr/irslackd>
irc_out :irslackd 353 = #general :hack5190 as_2 as as_3 hack5190
irc_in MODE #general
slack_in pong { type: 'pong', reply_to: 1 }
slack_in pong { type: 'pong', reply_to: 2 }

slack_in pong { type: 'pong', reply_to: 11 }
slack_in pong { type: 'pong', reply_to: 12 }
irc_in MODE #general
slack_out users.info { user: 'C9RBY2S4B' }
irc_in WHO #general
Trace: irslackd_err Failed onIrcWho: { Error: An API error occurred: user_not_found
    at got.post.catch.then (/home/bouncer/irslackd/node_modules/@slack/client/dist/WebClient.js:383:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'slackclient_platform_error',
  data: 
   { ok: false,
     error: 'user_not_found',
     scopes: [ 'read', 'client', 'identify', 'post' ],
     acceptedScopes: [ 'users:read', 'read' ] } }
    at Irslackd.logError (/home/bouncer/irslackd/lib/irslackd.js:526:13)
    at /home/bouncer/irslackd/lib/irslackd.js:622:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
slack_in pong { type: 'pong', reply_to: 13 }
slack_in pong { type: 'pong', reply_to: 14 }

**Comment by Hack5190** [comment]
slack_in pong { type: 'pong', reply_to: 206 }
slack_in pong { type: 'pong', reply_to: 207 }
slack_out users.info { user: 'C9RBY2S4B' }
irc_in WHO #general
slack_out users.info { user: 'C9QTYHTLH' }
irc_in WHO #random
slack_in pong { type: 'pong', reply_to: 208 }
Trace: irslackd_err Failed onIrcWho: { Error: An API error occurred: user_not_found
    at got.post.catch.then (/home/bouncer/irslackd/node_modules/@slack/client/dist/WebClient.js:383:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'slackclient_platform_error',
  data:
   { ok: false,
     error: 'user_not_found',
     scopes: [ 'read', 'client', 'identify', 'post' ],
     acceptedScopes: [ 'users:read', 'read' ] } }
    at Irslackd.logError (/home/bouncer/irslackd/lib/irslackd.js:526:13)
    at /home/bouncer/irslackd/lib/irslackd.js:622:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Trace: irslackd_err Failed onIrcWho: { Error: An API error occurred: user_not_found
    at got.post.catch.then (/home/bouncer/irslackd/node_modules/@slack/client/dist/WebClient.js:383:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 'slackclient_platform_error',
  data:
   { ok: false,
     error: 'user_not_found',
     scopes: [ 'read', 'client', 'identify', 'post' ],
     acceptedScopes: [ 'users:read', 'read' ] } }
    at Irslackd.logError (/home/bouncer/irslackd/lib/irslackd.js:526:13)
    at /home/bouncer/irslackd/lib/irslackd.js:622:18
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
slack_in pong { type: 'pong', reply_to: 209 }
slack_in pong { type: 'pong', reply_to: 210 }

**Comment by Hack5190** [comment]
Fixed
