### ISSUE TITLE
Error: Cannot find module '@slack/client'

### ISSUE THREAD

**Issue by d3ngar** [adsr/irslackd#53]
I followed the installation instructions, then, upon starting the "irslackd" I get this error message:

```
$ ./irslackd
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@slack/client'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/dengar/slack/irslackd/lib/irslackd.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

I am not familiar with these error codes. Any idea?

**Comment by d3ngar** [comment]
```
$ npm -v
6.4.1
$ node --version
v10.15.0
```

**Comment by d3ngar** [comment]
Okay, I forgot to do 
`$npm install`
