### ISSUE TITLE
if a private channel is deleted in slack, user was not dropped from irslackd channel

### ISSUE THREAD

**Issue by jcolson** [adsr/irslackd#66]
**Description**

**Steps to reproduce**
1. ...create channel, join it, with any client
2. ...use slack client, delete channel
3. ...irslackd user still shows being in channel and /part doesn't work

**Expected behavior**
user should be removed from channel and/or be able to /part a nonexistant channel

**Log output**
```
 1 Feb 27 16:43:48 vpc irslackd[1039]: slack_in user_typing { type: 'user_typing', channel: 'D43KMNF16', user: 'U0AAQ3HQ9' }
 2 Feb 27 16:43:48 vpc irslackd[1039]: slack_out conversations.leave { channel: 'CGJ9UEYUA' }
 3 Feb 27 16:43:48 vpc irslackd[1039]: irc_in PART #sev_sfr Buh-bye!
 4 Feb 27 16:43:48 vpc irslackd[1039]: Trace: irslackd_err Failed onIrcPart: Error: {
 5 Feb 27 16:43:48 vpc irslackd[1039]: "method": "conversations.leave",
 6 Feb 27 16:43:48 vpc irslackd[1039]: "options": {
 7 Feb 27 16:43:48 vpc irslackd[1039]: "channel": "CGJ9UEYUA"
 8 Feb 27 16:43:48 vpc irslackd[1039]: },
 9 Feb 27 16:43:48 vpc irslackd[1039]: "error": {
10 Feb 27 16:43:48 vpc irslackd[1039]: "code": "slackclient_platform_error",
11 Feb 27 16:43:48 vpc irslackd[1039]: "data": {
12 Feb 27 16:43:48 vpc irslackd[1039]: "ok": false,
13 Feb 27 16:43:48 vpc irslackd[1039]: "error": "channel_not_found",
14 Feb 27 16:43:48 vpc irslackd[1039]: "scopes": [
15 Feb 27 16:43:48 vpc irslackd[1039]: "read",
16 Feb 27 16:43:48 vpc irslackd[1039]: "client",
17 Feb 27 16:43:48 vpc irslackd[1039]: "admin",
18 Feb 27 16:43:48 vpc irslackd[1039]: "identify",
19 Feb 27 16:43:48 vpc irslackd[1039]: "post",
20 Feb 27 16:43:48 vpc irslackd[1039]: "apps"
21 Feb 27 16:43:48 vpc irslackd[1039]: ],
22 Feb 27 16:43:48 vpc irslackd[1039]: "acceptedScopes": [
23 Feb 27 16:43:48 vpc irslackd[1039]: "channels:write",
24 Feb 27 16:43:48 vpc irslackd[1039]: "groups:write",
25 Feb 27 16:43:48 vpc irslackd[1039]: "mpim:write",
26 Feb 27 16:43:48 vpc irslackd[1039]: "im:write",
27 Feb 27 16:43:48 vpc irslackd[1039]: "post"
28 Feb 27 16:43:48 vpc irslackd[1039]: ]
29 Feb 27 16:43:48 vpc irslackd[1039]: }
30 Feb 27 16:43:48 vpc irslackd[1039]: }
31 Feb 27 16:43:48 vpc irslackd[1039]: }
32 Feb 27 16:43:48 vpc irslackd[1039]: at WebClient.apiCallOrThrow (/home/ec2-user/src/irslackd/lib/irslackd.js:1268:13)
33 Feb 27 16:43:48 vpc irslackd[1039]: at <anonymous>
34 Feb 27 16:43:48 vpc irslackd[1039]: at process._tickCallback (internal/process/next_tick.js:189:7)
35 Feb 27 16:43:48 vpc irslackd[1039]: at Irslackd.logError (/home/ec2-user/src/irslackd/lib/irslackd.js:1059:13)
36 Feb 27 16:43:48 vpc irslackd[1039]: at res.catch (/home/ec2-user/src/irslackd/lib/irslackd.js:1231:18)
37 Feb 27 16:43:48 vpc irslackd[1039]: at <anonymous>
38 Feb 27 16:43:48 vpc irslackd[1039]: at process._tickCallback (internal/process/next_tick.js:189:7)
39 Feb 27 16:43:49 vpc irslackd[1039]: slack_in pong { type: 'pong', reply_to: 1564 }
40 Feb 27 16:43:49 vpc irslackd[1039]: slack_in pong { type: 'pong', reply_to: 25602 }
41 Feb 27 16:43:50 vpc irslackd[1039]: irc_in WHO #randomtest
```

**Client setup**
 - IRC client and version:quassel 13.1
 - IRC bouncer and version (if any):quassel 13.1
 - OS:amazon linux2

**Comment by adsr** [comment]
Tracking here https://github.com/adsr/irslackd/issues/75
